# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b1112d3bbf6fa0657e13ad563ebe8f704ccdad341c2bfbc26bb733a49f254973265597364ced6e301d48af3184c9ffd496707fdd006f4a15244688093ffdd41

test:
  secret_key_base: 32ee823d0bd3f507433899a648dbe90905fde614c274ae45d6eb5f8ea3e64312df55458295704116da5d0786fd61509e1dbbbf48ad2f105de9879e9087c89b87

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
